# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"timesthree": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://{santarabantoosoo}.github.io/{nbdev}/"

git_url = "https://github.com/{santarabantoosoo}/{nbdev}/tree/{branch}/"

def custom_doc_links(name): return None
